trigger:
  paths:
    exclude:
      - README.md

  tags:
    include:
      - v*

  branches:
    include:
      - master
      - dev


variables:
  vmImageName: ubuntu-latest


jobs:
  - job: Validation
    pool:
      vmImage: $(vmImageName)

    steps:
      - template: .ci/templates/node-version.yml
      - template: .ci/templates/node-packages.yml

      - task: Bash@3
        inputs:
          targetType: inline
          script: npm run check
        displayName: Check coding style

      - task: Bash@3
        inputs:
          targetType: inline
          script: npm run lint
        displayName: Check linter

  - job: Test
    pool:
      vmImage: $(vmImageName)

    steps:
      - template: .ci/templates/node-version.yml
      - template: .ci/templates/node-packages.yml
      - template: .ci/templates/setup-clasp.yml

      - task: Bash@3
        inputs:
          targetType: inline
          script: npm test
        displayName: Run tests

  - job: Deploy
    pool:
      vmImage: $(vmImageName)

    dependsOn:
      - Validation
      - Test
    condition: |
      and
      (
        in(dependencies.Validation.result, 'Succeeded'),
        in(dependencies.Test.result, 'Succeeded'),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
      )

    steps:
      - template: .ci/templates/node-version.yml
      - template: .ci/templates/node-packages.yml
      - template: .ci/templates/setup-clasp.yml

      - task: Bash@3
        name: gas
        inputs:
          targetType: inline
          script: |
            export WEB_DEPLOYMENT_ID="$(npm run update | tail -n 1 | cut -d" " -f2)"
            echo "##vso[task.setvariable variable=web-deployment-id;issecret=true;isoutput=true]$WEB_DEPLOYMENT_ID"
        displayName: Push changes and deploy
        env:
          GAS_API_DEPLOYMENT_ID: $(gas.api-deployment-id)

      - template: .ci/templates/awscli-cmd.yml
        parameters:
          command: |
            python3 -m awscli lambda update-function-configuration \
              --function-name $(aws.lambda-name) \
              --environment "Variables={SCRIPT_ID=$(gas.web-deployment-id)}"
          display: Update lambda config
